### ISSUE TITLE
Infinite loading of certain files

### ISSUE THREAD

**Issue by KeNNYDiViNE** [IllusionMods/KKManager#105]
Hello, after the last update... 
some mods are downloaded in a circle.
Because of this, the entire download stops
Specifically these files, surely there are more(

Yes, I checked, and there are many more mods that immediately start loading again every time after downloading (

![Снимок](https://user-images.githubusercontent.com/121106568/208700713-2dacca4c-accc-4ba7-99b6-4e7dc9a4a352.PNG)

Rolling back to the previous version helped

**Comment by ManlyMarco** [comment]
Can you test if this build fixes the issue? 
[kkm_test.zip](https://github.com/IllusionMods/KKManager/files/10297644/kkm_test.zip)

**Comment by Ankokuzura** [comment]
> Can you test if this build fixes the issue? [kkm_test.zip](https://github.com/IllusionMods/KKManager/files/10297644/kkm_test.zip)
> 
> Edit: The above build doesn't help, try this one instead [kkm_test.zip](https://github.com/IllusionMods/KKManager/files/10298987/kkm_test.zip)

i have tried both of that and still have same problem after 70 - 80 % it will reset to 20% sometime random can u please fix it thanks

**Comment by ManlyMarco** [comment]
Fixed in 0ce9604a3c4836f9acf0a9e49d0451f027ab5017

**Comment by KeNNYDiViNE** [comment]
With the new version of KKManager_v0.21.4, the problem is back again(

I'll have to switch back to the old version, by the way I don't know why, but p2p doesn't work for me(
